name: simple-chat
version: "1.0.0"
summary: Simple Chat
description: |
  simple-chat is a secure and serverless chat application for Unix based platforms.
  Messages are encrypted and broadcasted to the broadcast address using the UDP protocol. 
  Any user within the same network is able to read the messages and respond back.

icon: snap/gui/simple-chat.png

base: core20 
confinement: strict

apps:
  simple-chat:
    command: usr/local/bin/simple-chat

parts:
  simple-chat:
    plugin: make 
    source-type: git
    source: https://github.com/miladfarca/simple-chat
    build-packages:
      - gcc
      - make
      - libncurses5-dev 
      - libssl-dev

plugs:
  simple-chat-network:
    interface: network
